version: "3"

services:
  api:
    build: .
    env_file:
      - .env
    init: true
    volumes:
      - ./data:/code/data
      - shared:/opt

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./entry/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/web:/var/www:ro
      - shared:/opt:ro
    ports:
      - 80:80
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.holotagger.rule=Host(`holotagger.njkyu.com`)"
      - "traefik.http.routers.holotagger.tls=true"
      - "traefik.http.routers.holotagger.tls.certresolver=le"

volumes:
  shared: