version: "3"

services:
  app:
    build: .
    container_name: holotagger
    env_file:
      - .env
    init: true
    volumes:
      - ./data:/code/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.holotagger.rule=Host(`holotagger.njkyu.com`)"
      - "traefik.http.routers.holotagger.tls=true"
      - "traefik.http.routers.holotagger.tls.certresolver=le"
