version: "3"

services:
  api:
    build: .
    env_file:
      - .env
    init: true
    volumes:
    - ./data:/code/data
    - shared:/opt

  nginx:
    image: nginx:1.19-alpine
    volumes:
    - ./entry/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./app/web:/var/www:ro
    - shared:/opt:ro
    ports:
    - 80:80
    depends_on:
      - api

volumes:
  shared: